export const copy = {
  es: {
    nav: ['Servicios', 'Nuestra perspectiva', 'Cómo trabajamos'], contact: 'Conversemos',
    eyebrow: 'UNA PERSPECTIVA GLOBAL. UN ENFOQUE PERSONAL.', hero: ['Un mundo de', 'posibilidades', 'en aviación.'],
    intro: 'Conectamos experiencia, personas y recursos para encontrar la solución adecuada para cada aeronave, cada operación y cada cliente.',
    discover: 'Explorar nuestros servicios', scroll: 'Descubra Open World Aviation',
    segments: ['Business aviation', 'Aviación comercial y regional', 'Propietarios y operadores'],
    servicesLabel: '01 — NUESTRAS CAPACIDADES', servicesTitle: 'Su visión. Nuestra experiencia.',
    servicesIntro: 'Cinco áreas de especialización. Un único punto de contacto para acompañar sus decisiones aeronáuticas.', more: 'Conocer más',
    aboutLabel: '02 — NUESTRA PERSPECTIVA', aboutTitle: 'Una mirada integral.\nUn compromiso personal.',
    aboutText: 'La aviación requiere más que una solución aislada. Requiere comprender la operación, el negocio y las personas detrás de cada decisión.',
    aboutText2: 'En Open World Aviation combinamos experiencia operacional, visión empresarial y una red internacional para acompañar a propietarios, empresas, inversores y operadores.',
    values: [['Criterio independiente', 'Soluciones alineadas con sus objetivos.'], ['Conexiones globales', 'Los recursos adecuados, donde los necesite.'], ['Atención personal', 'Claridad y cercanía en cada etapa.']],
    processLabel: '03 — CÓMO TRABAJAMOS', processTitle: 'Todo comienza con\nuna buena conversación.',
    process: [['Comprender', 'Escuchamos sus necesidades y definimos los objetivos, el contexto y el alcance de su proyecto.'], ['Conectar', 'Identificamos alternativas y coordinamos los recursos y especialistas adecuados.'], ['Acompañar', 'Mantenemos una comunicación clara y un punto de contacto durante cada etapa del proceso.']],
    contactLabel: '04 — CONVERSEMOS', contactTitle: '¿Cuál es su\npróximo paso?', contactIntro: 'Una aeronave. Una operación. Una nueva oportunidad. Cuéntenos qué tiene en mente.',
    name: 'Nombre y apellido', email: 'Email', phone: 'Teléfono / WhatsApp', company: 'Empresa', service: 'Servicio de interés', choose: 'Seleccione un servicio', message: '¿Cómo podemos ayudarle?', optional: 'opcional',
    prepare: 'Preparar consulta', review: 'Su consulta, lista para revisar', edit: 'Editar datos', sendEmail: 'Continuar por email', sendWhatsapp: 'Continuar en WhatsApp', download: 'Descargar consulta',
    reviewNote: 'La consulta aún no se ha enviado. Revise los datos antes de continuar.', pendingContact: 'El contacto directo estará disponible próximamente. Puede guardar su consulta para enviarla más adelante.',
    privacyNotice: 'Al continuar, reconoce haber leído nuestra', privacy: 'Política de Privacidad', sensitive: 'No incluya documentos ni información sensible en este formulario.',
    footerText: 'Experiencia aeronáutica.\nPerspectiva global.', footerLinks: ['Privacidad', 'Términos de uso', 'Cookies', 'Aviso legal'],
    disclaimer: 'Las soluciones charter se coordinan a través de operadores calificados. El transportador identificado en la documentación definitiva conserva el control operacional del vuelo.',
    rights: 'Todos los derechos reservados.', close: 'Cerrar', menu: 'Abrir menú', consult: 'Consultar por este servicio', back: 'Volver al inicio',
    draft: 'Borrador para revisión', draftText: 'Este documento proviene del paquete legal suministrado. Los campos destacados requieren confirmación antes de su publicación definitiva.', englishControls: 'La versión inglesa prevalece ante diferencias de traducción.', copied: 'Consulta descargada. Aún no fue enviada.',
    meta: 'Gestión de aeronaves, charter y soporte de vuelo, venta y adquisición, consultoría y logística. Experiencia aeronáutica con perspectiva global.'
  },
  en: {
    nav: ['Our services', 'Our perspective', 'Our approach'], contact: 'Let’s talk',
    eyebrow: 'GLOBAL PERSPECTIVE. PERSONAL APPROACH.', hero: ['A world of', 'possibilities', 'in aviation.'],
    intro: 'Connecting expertise, people and resources to find the right solution for every aircraft, every operation and every client.',
    discover: 'Explore our services', scroll: 'Discover Open World Aviation',
    segments: ['Business aviation', 'Commercial & regional aviation', 'Owners & operators'],
    servicesLabel: '01 — OUR CAPABILITIES', servicesTitle: 'Your vision. Our expertise.', servicesIntro: 'Five areas of expertise. One point of contact to guide your aviation decisions.', more: 'Learn more',
    aboutLabel: '02 — OUR PERSPECTIVE', aboutTitle: 'A complete perspective.\nA personal commitment.',
    aboutText: 'Aviation calls for more than an isolated solution. It calls for understanding the operation, the business and the people behind every decision.',
    aboutText2: 'At Open World Aviation, we combine operational experience, business understanding and an international network to support owners, companies, investors and operators.',
    values: [['Independent thinking', 'Solutions aligned with your objectives.'], ['Global connections', 'The right resources, wherever you need them.'], ['Personal attention', 'Clarity and care at every stage.']],
    processLabel: '03 — OUR APPROACH', processTitle: 'It all starts with\na good conversation.',
    process: [['Understand', 'We listen to your needs and define the objectives, context and scope of your project.'], ['Connect', 'We identify options and coordinate the right resources and specialists.'], ['Support', 'We maintain clear communication and one point of contact throughout the process.']],
    contactLabel: '04 — LET’S TALK', contactTitle: 'What’s your\nnext move?', contactIntro: 'An aircraft. An operation. A new opportunity. Tell us what you have in mind.',
    name: 'Full name', email: 'Email', phone: 'Phone / WhatsApp', company: 'Company', service: 'Service of interest', choose: 'Select a service', message: 'How can we help?', optional: 'optional',
    prepare: 'Prepare inquiry', review: 'Your inquiry, ready to review', edit: 'Edit details', sendEmail: 'Continue by email', sendWhatsapp: 'Continue in WhatsApp', download: 'Download inquiry',
    reviewNote: 'Your inquiry has not been sent yet. Review your details before continuing.', pendingContact: 'Direct contact will be available soon. You can save your inquiry to send it later.',
    privacyNotice: 'By continuing, you acknowledge that you have read our', privacy: 'Privacy Policy', sensitive: 'Please do not include sensitive information or documents in this form.',
    footerText: 'Aviation expertise.\nGlobal perspective.', footerLinks: ['Privacy', 'Terms of use', 'Cookies', 'Legal disclaimer'],
    disclaimer: 'Charter solutions are coordinated through qualified operators. The carrier identified in the definitive documentation retains operational control of the flight.',
    rights: 'All rights reserved.', close: 'Close', menu: 'Open menu', consult: 'Ask about this service', back: 'Back to home',
    draft: 'Draft for review', draftText: 'This document comes from the supplied legal package. Highlighted fields require confirmation before final publication.', englishControls: 'The English version controls if translations differ.', copied: 'Inquiry downloaded. It has not been sent.',
    meta: 'Aircraft management, private charter and flight support, aircraft sales and acquisitions, aviation consulting and logistics. A global aviation perspective.'
  }
};
export const legalPaths = ['/privacy', '/terms', '/cookies', '/legal-disclaimer'];
export const contacts = {
  email: 'contact@openworldaviation.com',
  whatsapp: '13054305398',
  phone: '+1 (305) 430-5398',
  instagram: 'https://www.instagram.com/openworldaviation?stkn=MWs3aXd5OG9rZ29sag%3D%3D',
};
